# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
version: '3'
services:
 authService:
  image: chandusindhu/userauth:1.0
  restart: always
  network_mode: host
  container_name: authServiceCont
  depends_on:
   - mysql
  ports:
   - 8089:8089

 categoryService:
  image: chandusindhu/catagory:5.0
  restart: always
  network_mode: host
  container_name: categoryServiceContainer
  depends_on:
   - mongo
  ports:
   - 8083:8083

 reminderService:
  image: chandusindhu/reminder:3.0
  restart: always
  network_mode: host
  container_name: reminderServiceContainer
  depends_on:
   - mongo
  ports:
   - 8081:8081
   
 noteService:
  image: chandusindhu/note:4.0
  restart: always
  network_mode: host
  container_name: noteServiceContainer
  depends_on:
   - mongo
  ports:
   - 8082:8082
   
 userService:
  image: chandusindhu/user:2.0
  network_mode: host
  container_name: userServiceContainer
  depends_on:
   - mongo
  ports:
   - 8080:8080
   
 mysql:
  image: mysql:5.5
  ports:
   - 3306:3306
  container_name: mysql_container
  network_mode: host
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: userDb
   MYSQL_USER: approot
   MYSQL_PASSWORD: root
   MYSQL_URL: jdbc:mysql://mysql:3306/userDb

 mongo:
  image: mongo:3.2-jessie
  ports:
   - "27017:27017"
  container_name: mongo
  network_mode: host
  
