spring:
 data:
   mongodb:
#     authentication-database:
     # username: ${MONGO_USERNAME}
     # password: ${MONGO_PASSWORD}
     # database: ${MONGO_DATABASE}
     # port: ${MONGO_PORT}
     # host: ${MONGO_HOST}
     database: reminderDb
     port: 27017
     host: localhost
 application:
   name: reminder-service
server:
 port: 8081